### ISSUE TITLE
Can you upload a copy of the human36m dataset?

### ISSUE THREAD

**Issue by acfhs** [cbsudux/awesome-human-pose-estimation#5]

**Comment by cbsudux** [comment]
You can have a look at this [repo's](https://github.com/xingyizhou/pytorch-pose-hg-3d) dataset. It's a sampled version of human3.6m

**Comment by acfhs** [comment]
thanks




------------------ 原始邮件 ------------------
发件人: "Sudharshan Chandra Babu"<notifications@github.com>;
发送时间: 2019年2月23日(星期六) 晚上7:35
收件人: "cbsudux/awesome-human-pose-estimation"<awesome-human-pose-estimation@noreply.github.com>;
抄送: "2082649913"<2082649913@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [cbsudux/awesome-human-pose-estimation] Can you upload a copy ofthe human36m dataset? (#5)




You can have a look at this repo's dataset. It's a sampled version of human3.6m
